####create a review
post http://localhost:4000/review/
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsTmFtZSI6InN5bHZpYSBNb2d1dHUiLCJlbWFpbCI6InNpbHZpYTNAdGhlaml0dS5jb20iLCJpZCI6ImE5YTVlZTBiLWM4MmEtNGRmZC04MjQ1LTExN2JjMmM5ZmQ4YyIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MDAxNTE2MDcsImV4cCI6MTcwMDIzODAwN30.PMFR4ZhC1vWrvbmfwmz3fR86_dsVTC6Seb7yF2GSZjs
Content-Type: application/json

{
    "tour_id": "c6c05891-5304-4b0d-abba-57ec0f199240", 
    "reviewer_id" : "a9a5ee0b-c82a-4dfd-8245-117bc2c9fd8c", 
    "review_content" : "This is the best tour I have ever been to",
    "review_rating" : "5"
}

#####get all reviews

get http://localhost:4000/review/
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsTmFtZSI6InN5bHZpYSBNb2d1dHUiLCJlbWFpbCI6InNpbHZpYTNAdGhlaml0dS5jb20iLCJpZCI6ImE5YTVlZTBiLWM4MmEtNGRmZC04MjQ1LTExN2JjMmM5ZmQ4YyIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MDAxNTE2MDcsImV4cCI6MTcwMDIzODAwN30.PMFR4ZhC1vWrvbmfwmz3fR86_dsVTC6Seb7yF2GSZjs


#####get one review by id
get http://localhost:4000/review/900fb878-91c3-4b1e-8f16-615abbc385ff
token :eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsTmFtZSI6InN5bHZpYSBNb2d1dHUiLCJlbWFpbCI6InNpbHZpYTNAdGhlaml0dS5jb20iLCJpZCI6ImE5YTVlZTBiLWM4MmEtNGRmZC04MjQ1LTExN2JjMmM5ZmQ4YyIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MDAxNTE2MDcsImV4cCI6MTcwMDIzODAwN30.PMFR4ZhC1vWrvbmfwmz3fR86_dsVTC6Seb7yF2GSZjs

#####update review by ID

put http://localhost:4000/review
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsTmFtZSI6InN5bHZpYSBNb2d1dHUiLCJlbWFpbCI6InNpbHZpYTNAdGhlaml0dS5jb20iLCJpZCI6ImE5YTVlZTBiLWM4MmEtNGRmZC04MjQ1LTExN2JjMmM5ZmQ4YyIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MDAxNTE2MDcsImV4cCI6MTcwMDIzODAwN30.PMFR4ZhC1vWrvbmfwmz3fR86_dsVTC6Seb7yF2GSZjs
Content-Type: application/json

{
    "review_id": "900fb878-91c3-4b1e-8f16-615abbc385ff",
    "tour_id": "c6c05891-5304-4b0d-abba-57ec0f199240", 
    "reviewer_id" : "a9a5ee0b-c82a-4dfd-8245-117bc2c9fd8c", 
    "review_content" : "hii ni jaba",
    "review_rating" : "5"
}


##### delete review by ID
delete http://localhost:4000/review/900fb878-91c3-4b1e-8f16-615abbc385ff
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsTmFtZSI6InN5bHZpYSBNb2d1dHUiLCJlbWFpbCI6InNpbHZpYTNAdGhlaml0dS5jb20iLCJpZCI6ImE5YTVlZTBiLWM4MmEtNGRmZC04MjQ1LTExN2JjMmM5ZmQ4YyIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MDAxNTE2MDcsImV4cCI6MTcwMDIzODAwN30.PMFR4ZhC1vWrvbmfwmz3fR86_dsVTC6Seb7yF2GSZjs
